files:
  - source: /languages/en-GB/admin/*.ini
    translation: /languages/%locale%/admin/%original_file_name%
  - source: /languages/en-GB/site/*.ini
    translation: /languages/%locale%/site/%original_file_name%
