files:
  - source: /admin/*.ini
    translation: /languages/%locale_with_dash%/admin/%original_file_name%
  - source: /site/*.ini
    translation: /languages/%locale_with_dash%/site/%original_file_name%
